---
apiVersion: v1
kind: Namespace
metadata:
  name: nfsprovisioner-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nfsprovisioner-operators
  namespace: nfsprovisioner-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfs-provisioner-operator
  namespace: nfsprovisioner-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: nfs-provisioner-operator
  source: community-operators 
  sourceNamespace: openshift-marketplace 

