---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: 3scale-operators
  namespace: 3scale
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
  namespace: 3scale
spec:
  channel: threescale-2.13 
  installPlanApproval: Automatic
  name: 3scale-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
