---
apiVersion: v1
kind: Namespace
metadata:
  name: apicast-op
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: apicast-operators
  namespace: apicast-op
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicast-operator
  namespace: apicast-op
spec:
  channel: threescale-2.13 
  installPlanApproval: Automatic
  name: apicast-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
