apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: my-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.amq-streams-kafka.svc.cluster.local:9092
  topics:
  - my-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-consumer
