kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
     app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  #storageClassName: gp3-csi
  #volumeMode: Filesystem
